### ISSUE TITLE
Heartbeat support

### ISSUE THREAD

**Issue by aovestdipaperino** [tisonkun/kafka-api#9]
I think, still not 100% positive, this is required for the Spring Boot client; if I send a default response my Spring Boot app happily consumes the messages.
Request code is here: https://github.com/aovestdipaperino/kafka-api/blob/expiration/kafka-api/src/schemata/heartbeat_request.rs
Response code here: https://github.com/aovestdipaperino/kafka-api/blob/expiration/kafka-api/src/schemata/heartbeat_response.rs

**Comment by tisonkun** [comment]
Looks reasonable. Let me take a look in this week.

**Comment by tisonkun** [comment]
0.3.1 is out with this support
